# Generated by Django 6.0 on 2025-12-06 07:35

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone",
                    models.CharField(help_text="Used for sending SMS", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - Used for sending PDF version of invoices",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "db_table": "parents",
            },
        ),
    ]
