# Generated by Django 4.2.24 on 2025-12-08 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Parent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "phone",
                    models.CharField(help_text="Used for sending SMS", max_length=20),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional - Used for sending PDF version of invoices",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Parent",
                "verbose_name_plural": "Parents",
                "db_table": "parents",
            },
        ),
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=50)),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "streamA"),
                            ("B", "streamB"),
                            ("C", "streamC"),
                            ("D", "streamD"),
                        ],
                        max_length=10,
                        null=True,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("max_students", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                (
                    "admission_number",
                    models.CharField(
                        max_length=50, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "class_stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "streamA"),
                            ("B", "streamB"),
                            ("C", "streamC"),
                            ("D", "streamD"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("TERM1", "Term1"),
                            ("TERM2", "Term2"),
                            ("TERM3", "Term3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("billing_profile_active", models.BooleanField(default=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_class",
                        to="studentPortal.schoolclass",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="studentPortal.parent",
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="parent",
                        to="studentPortal.parent",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["admission_number"],
            },
        ),
        migrations.CreateModel(
            name="StudentProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "student",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="studentPortal.student",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="student_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
