# Generated by Django 4.2.24 on 2025-12-08 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentPortal", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
