# Generated by Django 6.0 on 2025-12-06 08:45

import django.db.models.deletion
import studentPortal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("studentPortal", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SchoolClass",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("class_name", models.CharField(max_length=50)),
                (
                    "stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "stream A"),
                            ("B", "stream B"),
                            ("C", "stream C"),
                            ("D", "stream D"),
                        ],
                        default=studentPortal.models.SchoolClass.Streams,
                        max_length=10,
                        null=True,
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("max_students", models.IntegerField()),
                ("is_active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("admission_number", models.CharField(max_length=50, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "middle_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("date_of_birth", models.DateField()),
                (
                    "class_stream",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("A", "stream A"),
                            ("B", "stream B"),
                            ("C", "stream C"),
                            ("D", "stream D"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "term",
                    models.CharField(
                        choices=[
                            ("TERM1", "Term1"),
                            ("TERM2", "Term2"),
                            ("TERM3", "Term3"),
                        ],
                        max_length=10,
                    ),
                ),
                ("billing_profile_active", models.BooleanField(default=True)),
                (
                    "class_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studentPortal.schoolclass",
                    ),
                ),
                (
                    "parent_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="studentPortal.parent",
                    ),
                ),
            ],
            options={
                "db_table": "students",
                "ordering": ["admission_number"],
            },
        ),
    ]
