# Generated by Django 4.2.24 on 2025-12-09 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("studentPortal", "0002_alter_student_email"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeStructure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_year", models.CharField(max_length=20)),
                ("tuition_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "lunch_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "transport_fee",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "other_fees",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school_class",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fee_structures",
                        to="studentPortal.schoolclass",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fee Structure",
                "verbose_name_plural": "Fee Structures",
                "db_table": "fee_structures",
                "unique_together": {("school_class", "academic_year")},
            },
        ),
    ]
